### ISSUE TITLE
Add prometheus.yml (ch.4) to the Github repo

### ISSUE THREAD

**Issue by natalie9200** [PacktPublishing/Learn-Grafana-10#10]
Hi,
it would be great if you could also add the prometheus.yml file from chapter 4 to the repo. When I copy it from the PDF the indentation is lost. Copying from the book directly on packtpub.com works, but the indentation in lines 13-15 seems to be wrong somehow.
Thanks!

**Comment by esalituro** [comment]
I apologize for the delay. The file has been added to the Chapter04/prometheus
